# Generated by Django 2.2.13 on 2020-06-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='alt_text',
            field=models.CharField(blank=True, help_text='This is assistive text for screen readers. This is very important to fill out on image-only posts.', max_length=1000, null=True),
        ),
    ]
