# Generated by Django 2.2.13 on 2020-07-01 19:53

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
