# Generated by Django 2.2.13 on 2020-08-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200705_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title'],
                'verbose_name_plural': 'categories'
            },
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, to='posts.Category'),
        ),
    ]
