# Generated by Django 2.2.15 on 2020-08-21 17:05
import secrets

from django.db import migrations, models


def migrate_identifier_forwards(apps, schema_editor):
    Post = apps.get_model('posts', 'post')
    for post in Post.objects.all():
        post.identifier = secrets.randbelow(2**31)
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='identifier',
            field=models.IntegerField(null=True),
        ),

        migrations.RunPython(
            migrate_identifier_forwards,
            migrations.RunPython.noop,
        ),

        migrations.AlterField(
            model_name='post',
            name='identifier',
            field=models.IntegerField(),
        ),
    ]
