# Generated by Django 2.2.15 on 2020-08-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
