# Generated by Django 2.2.15 on 2020-08-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20200824_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='online',
            field=models.BooleanField(default=False, help_text='Uncheck this to hide this post on the frontend.'),
        ),
    ]
