# Generated by Django 3.1.6 on 2021-02-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='opengraph_description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='post',
            name='opengraph_image',
            field=models.ImageField(blank=True, null=True, upload_to='opengraph-images', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='post',
            name='opengraph_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='title'),
        ),
    ]
