# Generated by Django 4.0 on 2022-01-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exogram', '0003_gram_commons_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gram',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
